#!/bin/bash

echo "docker-minecraft - '$(id -un):$(id -gn)'"

EULA=${EULA:-false}
MINECRAFT_HOME="/opt/minecraft"
MINECRAFT_VERSION=${MINECRAFT_VERSION}
TEMP_DIR="/temp"

get_paper() {
    echo "fetching paper $MINECRAFT_VERSION"
    mkdir $TEMP_DIR
    cd $TEMP_DIR || exit
    BUILD_NUMBER=$(curl -X 'GET' "https://papermc.io/api/v2/projects/paper/versions/${MINECRAFT_VERSION}" -H 'accept: application/json' | jq '.builds | last')
    echo "BUILD_NUMBER=$BUILD_NUMBER"
    DOWNLOAD_NAME=$(curl -X 'GET' "https://papermc.io/api/v2/projects/paper/versions/${MINECRAFT_VERSION}/builds/${BUILD_NUMBER}" -H 'accept: application/json' | jq -r '.downloads.application.name')
    echo "DOWNLOAD_NAME=$DOWNLOAD_NAME"
    wget -O paper.jar https://papermc.io/api/v2/projects/paper/versions/${MINECRAFT_VERSION}/builds/${BUILD_NUMBER}/downloads/${DOWNLOAD_NAME} && \
    cp paper.jar $MINECRAFT_HOME/paper.jar
}

write_eula() {
    echo 'writing eula'
    cd $MINECRAFT_HOME || exit
    echo "eula=$EULA" > $MINECRAFT_HOME/eula.txt
}

cleanup() {
    echo 'cleaning up' && \
    rm -rf $TEMP_DIR
}

echo 'executing script'

[ -d "/opt" ] && mkdir /opt
[ -d "$MINECRAFT_HOME" ] && mkdir $MINECRAFT_HOME

if [ ! -f "$MINECRAFT_HOME/paper.jar" ]; then
    cp /server.properties $MINECRAFT_HOME
    echo $DEFAULT_OP > $MINECRAFT_HOME/ops.txt
    get_paper && \
    cleanup
fi

write_eula

echo "starting up paper server"
java -Xms2G -Xmx2G -jar $MINECRAFT_HOME/paper.jar --nogui
