#!/bin/bash

echo "docker-minecraft - '$(id -un):$(id -gn)'"

EULA=${EULA:-false}
MINECRAFT_HOME="/opt/minecraft"
MINECRAFT_VERSION=${MINECRAFT_VERSION}
TEMP_DIR="/temp"

get_paper() {
    echo "fetching paper $MINECRAFT_VERSION"
    if [ ! -d "$TEMP_DIR" ]; then
        mkdir $TEMP_DIR
    fi
    cd $TEMP_DIR
    BUILD_NUMBER=$(curl -s https://api.papermc.io/v2/projects/paper/versions/${MINECRAFT_VERSION}/builds | \
        jq -r '.builds | map(select(.channel == "default") | .build) | .[-1]')
    echo "BUILD_NUMBER=$BUILD_NUMBER"
    JAR_NAME=paper-${MINECRAFT_VERSION}-${BUILD_NUMBER}.jar
    PAPERMC_URL="https://api.papermc.io/v2/projects/paper/versions/${MINECRAFT_VERSION}/builds/${BUILD_NUMBER}/downloads/${JAR_NAME}"
    echo "PAPERMC_URL=$PAPERMC_URL"
    curl -o paper.jar $PAPERMC_URL && \
        cp paper.jar $MINECRAFT_HOME/paper.jar
}

write_eula() {
    echo 'writing eula'
    cd $MINECRAFT_HOME
    echo "eula=$EULA" > $MINECRAFT_HOME/eula.txt
}

cleanup() {
    echo 'cleaning up' && \
    rm -rf $TEMP_DIR
}

echo 'executing script'

if [ ! -f "$MINECRAFT_HOME/paper.jar" ]; then
    cp /server.properties $MINECRAFT_HOME
    echo $DEFAULT_OP > $MINECRAFT_HOME/ops.txt
    get_paper && \
    cleanup
fi

write_eula

echo "starting up paper server"
java -Xms2G -Xmx2G -jar $MINECRAFT_HOME/paper.jar --nogui
